var PROPERTIES_TYPE_SCRIPT = 1;
var PROPERTIES_TYPE_USER = 2;
var PROPERTIES_TYPE_DOCUMENT = 3;

var LOG_SPREADSHEET_ID = "1l05UV303UTPuYOoTDkXkmBB3HqTbRBLitznZxZem02U";
var PROFILE_IMAGE_FILE_ID = "1KvZudA9OtE-PRPyY7kP567kjhWGJqUop";
var ADD_DRIVE_IMAGE_ID = "1Mh_uizD2jeJ72tIdQiD4Y8nzwi-CsozD";
var PERSONAL_PARENT_FOLDER_ID = "0B-PYJiOSewXLUE1obURNLURxX1k";
var PERSONAL_PLAN_TEMPLATE_DOC_ID = "1CWqLtG9G7GgfMzSP110LSRmaBnZlMtX0D3kNOuPZr6g";

var LOG_LEVEL_INFO = "INFO";
var LOG_LEVEL_WARN = "WARN";
var LOG_LEVEL_ERROR = "ERROR";